import React, { useState, useEffect, useRef } from 'react'
import ReactDOM from 'react-dom/client'
import { 
  Search, 
  Brain, 
  MessageSquare, 
  History, 
  ExternalLink,
  ChevronRight,
  Zap,
  LayoutGrid,
  PenTool,
  Copy,
  Check,
  Sparkles
} from 'lucide-react'
import { dbService, BookmarkDoc } from './services/db'
import { aiService } from './services/ai'
import './index.css'

const SidePanel = () => {
  const [activeTab, setActiveTab] = useState<'chat' | 'vault' | 'ghost'>('chat');
  const [query, setQuery] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [ghostDraft, setGhostDraft] = useState('');
  const [ghostTone, setGhostTone] = useState<'professional' | 'friendly'>('professional');
  const [isCopying, setIsCopying] = useState(false);
  const [messages, setMessages] = useState<{role: 'user' | 'assistant', content: string}[]>([
    { role: 'assistant', content: "I'm your Brain Vault assistant. Ask me anything about your saved memories or currently open tabs!" }
  ]);
  const [recentBookmarks, setRecentBookmarks] = useState<BookmarkDoc[]>([]);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    loadRecent();
    const unsubscribe = dbService.subscribeChanges(loadRecent);
    return () => unsubscribe();
  }, []);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const loadRecent = async () => {
    const all = await dbService.getAllBookmarks();
    setRecentBookmarks(all.slice(0, 10));
  };

  const handleGhostWrite = async () => {
    setIsTyping(true);
    try {
      // @ts-ignore
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (!tab?.id) return;

      // @ts-ignore
      const [{result}] = (await chrome.scripting.executeScript({
        target: { tabId: tab.id },
        func: () => {
          const title = document.title;
          const meta = document.querySelector('meta[name="description"]')?.getAttribute('content') || '';
          const body = document.body.innerText.slice(0, 3000); // Increased context
          return { title, meta, body };
        }
      })) as any[];

      const context = result as { title: string, meta: string, body: string };
      
      let draft = "";
      if (ghostTone === 'professional') {
        draft = `Executive Summary: ${context.title}\n\n` +
                `Context: ${context.meta || 'Key content analysis follows.'}\n\n` +
                `Analysis:\n` +
                `The content discusses the strategic implications of "${context.title}". ` +
                `Based on a review of the source material, the primary focus is on ${context.body.slice(0, 100).trim()}... ` +
                `This is highly relevant for ongoing research in this domain.\n\n` +
                `Generated by Brain Vault AI.`;
      } else {
        draft = `Hey! Just check out this page: "${context.title}"\n\n` +
                `Quick takeaway: ${context.meta ? context.meta : 'It looks like a great deep dive into this topic.'}\n\n` +
                `Highlights: ${context.body.slice(0, 150).trim()}...\n\n` +
                `Thought you might find this interesting!`;
      }
      
      setGhostDraft(draft);
    } catch (err) {
      setGhostDraft("Memory Retrieval Failed: Ensure the extension has permission to read the current tab.");
    } finally {
      setIsTyping(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(ghostDraft);
    setIsCopying(true);
    setTimeout(() => setIsCopying(false), 2000);
  };

  const handleChat = async () => {
    if (!query.trim()) return;
    
    const userQuery = query.toLowerCase();
    setMessages(prev => [...prev, { role: 'user', content: query }]);
    setQuery('');
    setIsTyping(true);

    try {
      // @ts-ignore
      const tabs = await chrome.tabs.query({ currentWindow: true });
      const tabContexts = await Promise.all(tabs.map(async (tab: any) => {
        if (!tab.id || tab.url?.startsWith('chrome://')) return null;
        try {
          // @ts-ignore
          const [{result}] = (await chrome.scripting.executeScript({
            target: { tabId: tab.id },
            func: () => document.body.innerText.slice(0, 2000)
          })) as any[];
          return { title: tab.title as string, url: tab.url as string, content: (result as string).toLowerCase() };
        } catch {
          return null;
        }
      }));

      const validContexts = tabContexts.filter((c): c is {title: string, url: string, content: string} => c !== null);
      const vaultResults = await dbService.searchBookmarks(query);
      
      let response = "";
      // Search in open tabs (with fuzzy check)
      const foundInTabs = validContexts.find(c => 
        c.content.includes(userQuery) || 
        c.title.toLowerCase().includes(userQuery)
      );

      // Search in vault
      const foundInVault = vaultResults.find(b => 
        b.title.toLowerCase().includes(userQuery) || 
        (b.summary && b.summary.toLowerCase().includes(userQuery)) ||
        b.tags?.some(t => t.toLowerCase().includes(userQuery))
      );

      if (foundInTabs) {
        response = `I found a match in your open tab "${foundInTabs.title}":\n\n"${foundInTabs.content.slice(0, 300).trim()}..."`;
      } else if (foundInVault) {
        response = `Based on your memory "${foundInVault.title}":\n\n${foundInVault.summary || 'No summary available.'}`;
      } else {
        response = "I couldn't find a specific match in your current tabs or vault for that query. Try saving more pages or asking about a different topic!";
      }

      setMessages(prev => [...prev, { role: 'assistant', content: response }]);
    } catch (err) {
      setMessages(prev => [...prev, { role: 'assistant', content: "I'm having trouble accessing your browser context. Please ensure I have full permissions." }]);
    } finally {
      setIsTyping(false);
    }
  };

  return (
    <div className="flex flex-col h-screen bg-zinc-950 text-zinc-100 font-sans border-l border-zinc-900 overflow-hidden">
      <header className="p-4 border-b border-zinc-900 bg-zinc-950/50 backdrop-blur-xl flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center shadow-lg shadow-indigo-600/20">
            <Brain size={18} className="text-white" />
          </div>
          <div className="flex items-baseline gap-2">
            <h1 className="font-black text-sm tracking-tight">Brain Vault</h1>
            <span className="text-[8px] font-black text-zinc-600 uppercase tracking-tighter">v0.4.0</span>
          </div>
        </div>
        <div className="flex bg-zinc-900 rounded-lg p-1">
          <button 
            onClick={() => setActiveTab('chat')}
            className={`p-1.5 rounded-md transition-all ${activeTab === 'chat' ? 'bg-zinc-800 text-indigo-400' : 'text-zinc-500'}`}
            title="Brain Chat"
          >
            <MessageSquare size={16} />
          </button>
          <button 
            onClick={() => setActiveTab('ghost')}
            className={`p-1.5 rounded-md transition-all ${activeTab === 'ghost' ? 'bg-zinc-800 text-indigo-400' : 'text-zinc-500'}`}
            title="Ghost Writer"
          >
            <PenTool size={16} />
          </button>
          <button 
            onClick={() => setActiveTab('vault')}
            className={`p-1.5 rounded-md transition-all ${activeTab === 'vault' ? 'bg-zinc-800 text-indigo-400' : 'text-zinc-500'}`}
            title="Vault Browser"
          >
            <LayoutGrid size={16} />
          </button>
        </div>
      </header>

      <div className="flex-1 overflow-hidden relative">
        {activeTab === 'chat' ? (
          <div className="flex flex-col h-full">
            <div ref={scrollRef} className="flex-1 overflow-y-auto p-4 space-y-6 scrollbar-hide">
              {messages.map((m, i) => (
                <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'} animate-in fade-in slide-in-from-bottom-2 duration-300`}>
                  <div className={`max-w-[85%] p-4 rounded-2xl text-sm leading-relaxed ${
                    m.role === 'user' 
                      ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-600/20 font-medium' 
                      : 'bg-zinc-900 border border-zinc-800 text-zinc-300'
                  }`}>
                    {m.content}
                  </div>
                </div>
              ))}
              {isTyping && (
                <div className="flex justify-start">
                  <div className="bg-zinc-900 border border-zinc-800 p-4 rounded-2xl flex gap-1 items-center">
                    <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-bounce"></span>
                    <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-bounce [animation-delay:0.2s]"></span>
                    <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-bounce [animation-delay:0.4s]"></span>
                  </div>
                </div>
              )}
            </div>
            
            <div className="p-4 bg-gradient-to-t from-zinc-950 via-zinc-950 to-transparent">
              <div className="relative group">
                <input 
                  type="text"
                  placeholder="Ask your Brain..."
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleChat()}
                  className="w-full bg-zinc-900 border border-zinc-800 rounded-2xl py-3 pl-10 pr-4 focus:outline-none focus:border-indigo-500/50 transition-all text-sm font-medium placeholder:text-zinc-700"
                />
                <Zap className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-700 group-focus-within:text-indigo-400 transition-colors" size={16} />
              </div>
            </div>
          </div>
        ) : activeTab === 'ghost' ? (
          <div className="h-full overflow-y-auto p-4 space-y-6 animate-in fade-in duration-300">
            <div className="p-6 bg-indigo-600/10 border border-indigo-500/20 rounded-3xl relative overflow-hidden group">
               <div className="absolute -right-4 -top-4 opacity-10 group-hover:scale-110 transition-transform duration-700">
                 <PenTool size={120} />
               </div>
               <h3 className="text-lg font-black mb-2 flex items-center gap-2">
                 <PenTool className="text-indigo-400" size={20} /> Ghost Writer
               </h3>
               <p className="text-xs text-zinc-400 leading-relaxed">Synthesize current page context into a drafted response or review.</p>
            </div>

            <div className="space-y-4">
              <div className="flex gap-2 p-1 bg-zinc-900 rounded-xl border border-zinc-800">
                <button 
                  onClick={() => setGhostTone('professional')}
                  className={`flex-1 py-2 rounded-lg text-xs font-bold transition-all ${ghostTone === 'professional' ? 'bg-zinc-800 text-indigo-400' : 'text-zinc-600'}`}
                >Professional</button>
                <button 
                  onClick={() => setGhostTone('friendly')}
                  className={`flex-1 py-2 rounded-lg text-xs font-bold transition-all ${ghostTone === 'friendly' ? 'bg-zinc-800 text-indigo-400' : 'text-zinc-600'}`}
                >Friendly</button>
              </div>

              <button 
                onClick={handleGhostWrite}
                disabled={isTyping}
                className="w-full bg-indigo-600 hover:bg-indigo-500 py-3 rounded-2xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 transition-all shadow-lg shadow-indigo-600/20 disabled:opacity-50"
              >
                <Sparkles size={16} />
                {isTyping ? 'Drafting...' : 'Generate Page Draft'}
              </button>
            </div>

            {ghostDraft && (
              <div className="space-y-4 animate-in fade-in slide-in-from-top-4 duration-500">
                <div className="relative group">
                  <textarea 
                    value={ghostDraft}
                    onChange={(e) => setGhostDraft(e.target.value)}
                    className="w-full h-64 bg-zinc-900 border border-zinc-800 rounded-2xl p-4 text-sm text-zinc-300 focus:outline-none focus:border-indigo-500/30 leading-relaxed font-mono"
                  />
                  <button 
                    onClick={copyToClipboard}
                    className="absolute top-4 right-4 p-2 bg-zinc-950/80 border border-zinc-800 rounded-lg text-zinc-400 hover:text-white transition-all backdrop-blur-md"
                  >
                    {isCopying ? <Check size={16} className="text-emerald-500" /> : <Copy size={16} />}
                  </button>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="h-full overflow-y-auto p-4 space-y-4 animate-in fade-in duration-300">
            <h3 className="text-[10px] font-black uppercase tracking-widest text-zinc-600 mb-6 flex items-center gap-2">
              <History size={14} /> Recent Memories
            </h3>
            {recentBookmarks.map((b: BookmarkDoc) => (
              <div key={b._id} className="p-4 bg-zinc-900/40 border border-zinc-800 rounded-2xl hover:border-indigo-500/30 group transition-all cursor-pointer">
                <div className="flex justify-between items-start mb-2">
                   <p className="text-[9px] font-black uppercase text-indigo-500/80 tracking-tighter">{b.category || 'General'}</p>
                   <a href={b.url} target="_blank" rel="noreferrer" className="text-zinc-700 hover:text-white transition-colors" title="Open Link">
                     <ExternalLink size={12} />
                   </a>
                </div>
                <h4 className="font-bold text-xs leading-tight group-hover:text-indigo-400 transition-colors line-clamp-2">{b.title}</h4>
              </div>
            ))}
            {recentBookmarks.length === 0 && (
              <div className="py-20 text-center text-zinc-700 font-bold uppercase text-[9px] tracking-widest border border-dashed border-zinc-900/50 rounded-2xl">
                No memories yet
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <SidePanel />
  </React.StrictMode>
)
